language: csharp
solution: XML.sln
language: csharp
solution: solution-name.sln
install:
  - nuget restore XML.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release XML.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./test/bin/Release/test.dll
